### ISSUE TITLE
Deploy to a better URL

### ISSUE THREAD

**Issue by anjor** [data-preservation-programs/fil-onboarding-report#12]

**Comment by jbenet** [comment]
the app is currently using streamlit. IDK how tied we are to that platform, or what work it entails to do something else.

From https://discuss.streamlit.io/t/custom-domain-for-streamlit-sharing/8751/17 -- it looks like streamlit does not allow custom domains, so the two approaches people use are:
- iframe into another domain (varying reports of success)
- redirect (less good, but can work)

I think: 
- iframe may be the easiest path for now
- log a feat request w/ streamlit that we may move off because it doesn't let us use subdomains.

**Comment by anjor** [comment]
@APiligrim has done this already, it's deployed at https://filecoin-tracker.com/ on render using the docker image.

**Comment by jbenet** [comment]
adjust name to be more specific to data onboarding
